In [148]:
import pandas as pd
import numpy as np

In [149]:
df_patients = pd.read_csv(r"C:\Users\pskir\OneDrive\Desktop\Optum Stratethon\Datalatest.csv")

In [150]:
pd.set_option('display.max_columns',100)
#df_patients.head(20)

In [151]:
df_patients.drop(["BIRTHDATE",'DEATHDATE','Column14','Column1','Column4','Column3',
                  'Column5','Column6','Column7','Column8','Column9','Column10','Column11',
                  'Column12','Column13','Column14','Column15','Column2','Column16'],axis=1,inplace=True)

In [152]:
df_patients.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1172 entries, 0 to 1171
Data columns (total 28 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Id                        1171 non-null   object
 1   Dead                      1171 non-null   float64
 2   Age                       1171 non-null   float64
 3   SUFFIX                    1171 non-null   float64
 4   MARITAL                   1171 non-null   float64
 5   RACE                      1171 non-null   float64
 6   ETHNICITY                 1171 non-null   float64
 7   GENDER                    1171 non-null   float64
 8   County                    1171 non-null   object
 9   ZIP                       1171 non-null   float64
 10  HEALTHCARE_EXPENSES       1171 non-null   float64
 11  HEALTHCARE_COVERAGE       1171 non-null   float64
 12  Latex allergy             1172 non-null   int64
 13  Shellfish allergy         1172 non-null   int64
 14  Allergy to mould          1172 non-null   int64
 15  Dander (animal) allergy   1172 non-null   int64
 16  Allergy to grass pollen   1172 non-null   int64
 17  Allergy to tree pollen    1172 non-null   int64
 18  Allergy to soya           1172 non-null   int64
 19  Allergy to fish           1172 non-null   int64
 20  House dust mite allergy   1172 non-null   int64
 21  Allergy to eggs           1172 non-null   int64
 22  Allergy to wheat          1172 non-null   int64
 23  Allergy to peanuts        1172 non-null   int64
 24  Allergy to dairy product  1172 non-null   int64
 25  Allergy to nut            1172 non-null   int64
 26  Allergy to bee venom      1172 non-null   int64
 27  Conditions                1171 non-null   float64
dtypes: float64(11), int64(15), object(2)
memory usage: 256.5+ KB

In [153]:
df_patients.drop([1171],inplace=True)
#df_patients.tail()

In [154]:
df_imaging_studies = pd.read_csv(r"C:\Users\pskir\Downloads\6180e4c10462e_Case_Files\Case Files\sample_date_csv (1)\csv\imaging_studies.csv")

In [155]:
#df_imaging_studies

In [156]:
df_imaging_studies.drop(columns=['DATE','Id','ENCOUNTER','BODYSITE_DESCRIPTION',
                                 'MODALITY_DESCRIPTION','SOP_CODE','SOP_DESCRIPTION'],inplace=True)

In [157]:
df_imaging_studies=df_imaging_studies.groupby('PATIENT', as_index=False).agg(lambda x: x.tolist())

In [158]:
df_imaging_studies = df_imaging_studies.rename(columns = {"PATIENT" : "Id"})

In [159]:
df = pd.merge(df_patients,df_imaging_studies,how="left",on='Id')

In [160]:
#df

In [161]:
df_medications = pd.read_csv(r"C:\Users\pskir\Downloads\6180e4c10462e_Case_Files\Case Files\sample_date_csv (1)\csv\medications.csv")

In [162]:
#df_medications

In [163]:
df_medications.drop(df_medications.columns[[0,1,3,4,6,7,8,9,10,11,12]],axis=1,inplace=True)

In [164]:
#df_medications

In [165]:
df_medications = df_medications.groupby('PATIENT', as_index=False).agg(lambda x: x.tolist())

In [166]:
#df_medications

In [167]:
df_medications = df_medications.rename(columns = {"PATIENT" : "Id"})

In [168]:
df = pd.merge(df,df_medications,how="left",on='Id')

In [169]:
df

,Id,Dead,Age,SUFFIX,MARITAL,RACE,ETHNICITY,GENDER,County,ZIP,HEALTHCARE_EXPENSES,HEALTHCARE_COVERAGE,Latex allergy,Shellfish allergy,Allergy to mould,Dander (animal) allergy,Allergy to grass pollen,Allergy to tree pollen,Allergy to soya,Allergy to fish,House dust mite allergy,Allergy to eggs,Allergy to wheat,Allergy to peanuts,Allergy to dairy product,Allergy to nut,Allergy to bee venom,Conditions,BODYSITE_CODE,MODALITY_CODE,CODE
0,1d604da9-9a81-4ba9-80c2-de3375d59b40,0.0,32.0,0.0,2.0,1.0,0.0,0.0,Hampden,1013.0,271227.08,1334.88,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.000000,NaN,NaN,"[562251, 562251]"
1,034e9e3b-2def-4559-bb2a-7850888ae060,0.0,37.0,0.0,2.0,1.0,1.0,0.0,Middlesex,2143.0,793946.01,3204.49,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-0.235098,NaN,NaN,[313782]
2,10339b10-3cd1-4ac3-ac13-ec26728cb592,0.0,29.0,0.0,2.0,1.0,1.0,0.0,Hampden,1020.0,574111.90,2606.40,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-0.235113,NaN,NaN,"[313782, 849574, 313782]"
3,8d4c4326-e9de-4f45-9a4c-f8c36bff89ae,0.0,43.0,0.0,2.0,1.0,1.0,1.0,Middlesex,1851.0,935630.30,8756.19,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-0.235100,NaN,NaN,"[389221, 389221, 748856, 389221, 1534809, 9789..."
4,f5dcd418-09fe-4a2f-baa0-3da800bd8c3a,0.0,25.0,0.0,0.0,1.0,1.0,0.0,Suffolk,2135.0,598763.07,3772.20,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-0.235101,NaN,NaN,[313782]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1166,023a7d29-32b3-4db5-89c8-b88bd7582ec0,0.0,99.0,0.0,2.0,3.0,0.0,1.0,Middlesex,2141.0,1622314.87,32086.31,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-0.235103,NaN,NaN,"[314231, 314231, 314231, 314231, 314231, 31423..."
1167,1fc8dafd-90e5-44d6-9179-81156c0ea083,0.0,44.0,0.0,1.0,1.0,1.0,0.0,Essex,1915.0,979724.25,3130.52,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-0.235087,NaN,NaN,[834102]
1168,6d048a56-edb8-4f29-891d-7a84d75a8e78,1.0,91.0,0.0,1.0,1.0,1.0,1.0,Norfolk,0.0,1560540.35,52391.24,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-0.235097,NaN,NaN,"[895994, 2123111, 895994, 2123111, 895994, 212..."
1169,fca3178e-fb68-41c3-8598-702d3ca68b96,1.0,75.0,0.0,2.0,1.0,1.0,1.0,Norfolk,2062.0,1375833.47,13157.00,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-0.235090,"[8205005, 261179002, 51185008, 261179002, 5118...","[DX, US, CR, US, CR, US, DX]","[2001499, 243670, 313782, 866414, 313988, 1719..."
1170,fc817953-cc8b-45db-9c85-7c0ced8fa90d,0.0,107.0,0.0,2.0,1.0,1.0,1.0,Norfolk,2090.0,1510158.34,26565.65,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-0.235093,NaN,NaN,NaN

In [170]:
df_procedures = pd.read_csv(r"C:\Users\pskir\Downloads\6180e4c10462e_Case_Files\Case Files\sample_date_csv (1)\csv\procedures.csv")

In [171]:
df_procedures.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34981 entries, 0 to 34980
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   DATE               34981 non-null  object
 1   PATIENT            34981 non-null  object
 2   ENCOUNTER          34981 non-null  object
 3   CODE               34981 non-null  int64
 4   DESCRIPTION        34981 non-null  object
 5   BASE_COST          34981 non-null  float64
 6   REASONCODE         19437 non-null  float64
 7   REASONDESCRIPTION  19437 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 2.1+ MB

In [172]:
df_procedures.drop(["DATE","ENCOUNTER","DESCRIPTION","BASE_COST","REASONCODE","REASONDESCRIPTION"],axis=1,inplace=True)

In [173]:
df_procedures=df_procedures.groupby('PATIENT', as_index=False).agg(lambda x: x.tolist())

In [174]:
df_procedures = df_procedures.rename(columns = {"PATIENT" : "Id"})

In [175]:
df = pd.merge(df,df_procedures,how="left",on='Id')

In [176]:
df

,Id,Dead,Age,SUFFIX,MARITAL,RACE,ETHNICITY,GENDER,County,ZIP,HEALTHCARE_EXPENSES,HEALTHCARE_COVERAGE,Latex allergy,Shellfish allergy,Allergy to mould,Dander (animal) allergy,Allergy to grass pollen,Allergy to tree pollen,Allergy to soya,Allergy to fish,House dust mite allergy,Allergy to eggs,Allergy to wheat,Allergy to peanuts,Allergy to dairy product,Allergy to nut,Allergy to bee venom,Conditions,BODYSITE_CODE,MODALITY_CODE,CODE_x,CODE_y
0,1d604da9-9a81-4ba9-80c2-de3375d59b40,0.0,32.0,0.0,2.0,1.0,0.0,0.0,Hampden,1013.0,271227.08,1334.88,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.000000,NaN,NaN,"[562251, 562251]",[430193006]
1,034e9e3b-2def-4559-bb2a-7850888ae060,0.0,37.0,0.0,2.0,1.0,1.0,0.0,Middlesex,2143.0,793946.01,3204.49,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-0.235098,NaN,NaN,[313782],"[430193006, 430193006]"
2,10339b10-3cd1-4ac3-ac13-ec26728cb592,0.0,29.0,0.0,2.0,1.0,1.0,0.0,Hampden,1020.0,574111.90,2606.40,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-0.235113,NaN,NaN,"[313782, 849574, 313782]","[430193006, 288086009, 430193006, 269911007, 4..."
3,8d4c4326-e9de-4f45-9a4c-f8c36bff89ae,0.0,43.0,0.0,2.0,1.0,1.0,1.0,Middlesex,1851.0,935630.30,8756.19,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-0.235100,NaN,NaN,"[389221, 389221, 748856, 389221, 1534809, 9789...","[169553002, 65200003, 301807007, 169553002, 16..."
4,f5dcd418-09fe-4a2f-baa0-3da800bd8c3a,0.0,25.0,0.0,0.0,1.0,1.0,0.0,Suffolk,2135.0,598763.07,3772.20,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-0.235101,NaN,NaN,[313782],"[430193006, 117015009, 117015009, 430193006, 2..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1166,023a7d29-32b3-4db5-89c8-b88bd7582ec0,0.0,99.0,0.0,2.0,3.0,0.0,1.0,Middlesex,2141.0,1622314.87,32086.31,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-0.235103,NaN,NaN,"[314231, 314231, 314231, 314231, 314231, 31423...","[180325003, 180325003, 180325003, 180325003, 1..."
1167,1fc8dafd-90e5-44d6-9179-81156c0ea083,0.0,44.0,0.0,1.0,1.0,1.0,0.0,Essex,1915.0,979724.25,3130.52,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-0.235087,NaN,NaN,[834102],"[430193006, 430193006]"
1168,6d048a56-edb8-4f29-891d-7a84d75a8e78,1.0,91.0,0.0,1.0,1.0,1.0,1.0,Norfolk,0.0,1560540.35,52391.24,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-0.235097,NaN,NaN,"[895994, 2123111, 895994, 2123111, 895994, 212...","[430193006, 71651007, 35025007, 90226004, 7165..."
1169,fca3178e-fb68-41c3-8598-702d3ca68b96,1.0,75.0,0.0,2.0,1.0,1.0,1.0,Norfolk,2062.0,1375833.47,13157.00,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-0.235090,"[8205005, 261179002, 51185008, 261179002, 5118...","[DX, US, CR, US, CR, US, DX]","[2001499, 243670, 313782, 866414, 313988, 1719...","[40701008, 433112001, 73761001, 430193006, 430..."
1170,fc817953-cc8b-45db-9c85-7c0ced8fa90d,0.0,107.0,0.0,2.0,1.0,1.0,1.0,Norfolk,2090.0,1510158.34,26565.65,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-0.235093,NaN,NaN,NaN,"[430193006, 430193006, 430193006, 430193006, 4..."

In [177]:
df = df.rename(columns = {"CODE_x" : "Medications","CODE_y" : "Procedures"})

In [178]:
df

,Id,Dead,Age,SUFFIX,MARITAL,RACE,ETHNICITY,GENDER,County,ZIP,HEALTHCARE_EXPENSES,HEALTHCARE_COVERAGE,Latex allergy,Shellfish allergy,Allergy to mould,Dander (animal) allergy,Allergy to grass pollen,Allergy to tree pollen,Allergy to soya,Allergy to fish,House dust mite allergy,Allergy to eggs,Allergy to wheat,Allergy to peanuts,Allergy to dairy product,Allergy to nut,Allergy to bee venom,Conditions,BODYSITE_CODE,MODALITY_CODE,Medications,Procedures
0,1d604da9-9a81-4ba9-80c2-de3375d59b40,0.0,32.0,0.0,2.0,1.0,0.0,0.0,Hampden,1013.0,271227.08,1334.88,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.000000,NaN,NaN,"[562251, 562251]",[430193006]
1,034e9e3b-2def-4559-bb2a-7850888ae060,0.0,37.0,0.0,2.0,1.0,1.0,0.0,Middlesex,2143.0,793946.01,3204.49,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-0.235098,NaN,NaN,[313782],"[430193006, 430193006]"
2,10339b10-3cd1-4ac3-ac13-ec26728cb592,0.0,29.0,0.0,2.0,1.0,1.0,0.0,Hampden,1020.0,574111.90,2606.40,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-0.235113,NaN,NaN,"[313782, 849574, 313782]","[430193006, 288086009, 430193006, 269911007, 4..."
3,8d4c4326-e9de-4f45-9a4c-f8c36bff89ae,0.0,43.0,0.0,2.0,1.0,1.0,1.0,Middlesex,1851.0,935630.30,8756.19,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-0.235100,NaN,NaN,"[389221, 389221, 748856, 389221, 1534809, 9789...","[169553002, 65200003, 301807007, 169553002, 16..."
4,f5dcd418-09fe-4a2f-baa0-3da800bd8c3a,0.0,25.0,0.0,0.0,1.0,1.0,0.0,Suffolk,2135.0,598763.07,3772.20,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-0.235101,NaN,NaN,[313782],"[430193006, 117015009, 117015009, 430193006, 2..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1166,023a7d29-32b3-4db5-89c8-b88bd7582ec0,0.0,99.0,0.0,2.0,3.0,0.0,1.0,Middlesex,2141.0,1622314.87,32086.31,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-0.235103,NaN,NaN,"[314231, 314231, 314231, 314231, 314231, 31423...","[180325003, 180325003, 180325003, 180325003, 1..."
1167,1fc8dafd-90e5-44d6-9179-81156c0ea083,0.0,44.0,0.0,1.0,1.0,1.0,0.0,Essex,1915.0,979724.25,3130.52,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-0.235087,NaN,NaN,[834102],"[430193006, 430193006]"
1168,6d048a56-edb8-4f29-891d-7a84d75a8e78,1.0,91.0,0.0,1.0,1.0,1.0,1.0,Norfolk,0.0,1560540.35,52391.24,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-0.235097,NaN,NaN,"[895994, 2123111, 895994, 2123111, 895994, 212...","[430193006, 71651007, 35025007, 90226004, 7165..."
1169,fca3178e-fb68-41c3-8598-702d3ca68b96,1.0,75.0,0.0,2.0,1.0,1.0,1.0,Norfolk,2062.0,1375833.47,13157.00,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-0.235090,"[8205005, 261179002, 51185008, 261179002, 5118...","[DX, US, CR, US, CR, US, DX]","[2001499, 243670, 313782, 866414, 313988, 1719...","[40701008, 433112001, 73761001, 430193006, 430..."
1170,fc817953-cc8b-45db-9c85-7c0ced8fa90d,0.0,107.0,0.0,2.0,1.0,1.0,1.0,Norfolk,2090.0,1510158.34,26565.65,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-0.235093,NaN,NaN,NaN,"[430193006, 430193006, 430193006, 430193006, 4..."

In [179]:
final_df = df.iloc[:,[0,1,2,4,5,6,7,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,-2,-1]]

In [180]:
final_df

,Id,Dead,Age,MARITAL,RACE,ETHNICITY,GENDER,Latex allergy,Shellfish allergy,Allergy to mould,Dander (animal) allergy,Allergy to grass pollen,Allergy to tree pollen,Allergy to soya,Allergy to fish,House dust mite allergy,Allergy to eggs,Allergy to wheat,Allergy to peanuts,Allergy to dairy product,Allergy to nut,Allergy to bee venom,Medications,Procedures
0,1d604da9-9a81-4ba9-80c2-de3375d59b40,0.0,32.0,2.0,1.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,"[562251, 562251]",[430193006]
1,034e9e3b-2def-4559-bb2a-7850888ae060,0.0,37.0,2.0,1.0,1.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,[313782],"[430193006, 430193006]"
2,10339b10-3cd1-4ac3-ac13-ec26728cb592,0.0,29.0,2.0,1.0,1.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,"[313782, 849574, 313782]","[430193006, 288086009, 430193006, 269911007, 4..."
3,8d4c4326-e9de-4f45-9a4c-f8c36bff89ae,0.0,43.0,2.0,1.0,1.0,1.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,"[389221, 389221, 748856, 389221, 1534809, 9789...","[169553002, 65200003, 301807007, 169553002, 16..."
4,f5dcd418-09fe-4a2f-baa0-3da800bd8c3a,0.0,25.0,0.0,1.0,1.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,[313782],"[430193006, 117015009, 117015009, 430193006, 2..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1166,023a7d29-32b3-4db5-89c8-b88bd7582ec0,0.0,99.0,2.0,3.0,0.0,1.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,"[314231, 314231, 314231, 314231, 314231, 31423...","[180325003, 180325003, 180325003, 180325003, 1..."
1167,1fc8dafd-90e5-44d6-9179-81156c0ea083,0.0,44.0,1.0,1.0,1.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,[834102],"[430193006, 430193006]"
1168,6d048a56-edb8-4f29-891d-7a84d75a8e78,1.0,91.0,1.0,1.0,1.0,1.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,"[895994, 2123111, 895994, 2123111, 895994, 212...","[430193006, 71651007, 35025007, 90226004, 7165..."
1169,fca3178e-fb68-41c3-8598-702d3ca68b96,1.0,75.0,2.0,1.0,1.0,1.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,"[2001499, 243670, 313782, 866414, 313988, 1719...","[40701008, 433112001, 73761001, 430193006, 430..."
1170,fc817953-cc8b-45db-9c85-7c0ced8fa90d,0.0,107.0,2.0,1.0,1.0,1.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,"[430193006, 430193006, 430193006, 430193006, 4..."

In [181]:
row=-1
for x in final_df["Medications"]:
    #print(x)
    row += 1
    if(type(x)==float):
        continue
    final_df.at[row,'Medications']=list(set(x))

In [182]:
row=-1
for x in final_df["Procedures"]:
    #print(x)
    row += 1
    if(type(x)==float):
        continue
    final_df.at[row,'Procedures']=list(set(x))

In [183]:
final_df

,Id,Dead,Age,MARITAL,RACE,ETHNICITY,GENDER,Latex allergy,Shellfish allergy,Allergy to mould,Dander (animal) allergy,Allergy to grass pollen,Allergy to tree pollen,Allergy to soya,Allergy to fish,House dust mite allergy,Allergy to eggs,Allergy to wheat,Allergy to peanuts,Allergy to dairy product,Allergy to nut,Allergy to bee venom,Medications,Procedures
0,1d604da9-9a81-4ba9-80c2-de3375d59b40,0.0,32.0,2.0,1.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,[562251],[430193006]
1,034e9e3b-2def-4559-bb2a-7850888ae060,0.0,37.0,2.0,1.0,1.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,[313782],[430193006]
2,10339b10-3cd1-4ac3-ac13-ec26728cb592,0.0,29.0,2.0,1.0,1.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,"[849574, 313782]","[288086009, 430193006, 269911007]"
3,8d4c4326-e9de-4f45-9a4c-f8c36bff89ae,0.0,43.0,2.0,1.0,1.0,1.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,"[389221, 978950, 748856, 1534809, 1000126]","[65200003, 76601001, 169553002, 430193006, 301..."
4,f5dcd418-09fe-4a2f-baa0-3da800bd8c3a,0.0,25.0,0.0,1.0,1.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,[313782],"[117015009, 430193006, 269911007]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1166,023a7d29-32b3-4db5-89c8-b88bd7582ec0,0.0,99.0,2.0,3.0,0.0,1.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,"[855332, 197604, 314231, 313782, 897718]","[180325003, 430193006]"
1167,1fc8dafd-90e5-44d6-9179-81156c0ea083,0.0,44.0,1.0,1.0,1.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,[834102],[430193006]
1168,6d048a56-edb8-4f29-891d-7a84d75a8e78,1.0,91.0,1.0,1.0,1.0,1.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,"[313185, 895994, 313782, 2123111]","[430193006, 35025007, 71651007, 90226004, 2699..."
1169,fca3178e-fb68-41c3-8598-702d3ca68b96,1.0,75.0,2.0,1.0,1.0,1.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,"[313988, 866414, 313782, 243670, 1719286, 2001...","[433112001, 433236007, 312681000, 73761001, 39..."
1170,fc817953-cc8b-45db-9c85-7c0ced8fa90d,0.0,107.0,2.0,1.0,1.0,1.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,[430193006]

In [184]:
final_df["Medications"].fillna(0,inplace=True)

D:\Anaconda\lib\site-packages\pandas\core\series.py:4517: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().fillna(

In [185]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1171 entries, 0 to 1170
Data columns (total 24 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Id                        1171 non-null   object
 1   Dead                      1171 non-null   float64
 2   Age                       1171 non-null   float64
 3   MARITAL                   1171 non-null   float64
 4   RACE                      1171 non-null   float64
 5   ETHNICITY                 1171 non-null   float64
 6   GENDER                    1171 non-null   float64
 7   Latex allergy             1171 non-null   int64
 8   Shellfish allergy         1171 non-null   int64
 9   Allergy to mould          1171 non-null   int64
 10  Dander (animal) allergy   1171 non-null   int64
 11  Allergy to grass pollen   1171 non-null   int64
 12  Allergy to tree pollen    1171 non-null   int64
 13  Allergy to soya           1171 non-null   int64
 14  Allergy to fish           1171 non-null   int64
 15  House dust mite allergy   1171 non-null   int64
 16  Allergy to eggs           1171 non-null   int64
 17  Allergy to wheat          1171 non-null   int64
 18  Allergy to peanuts        1171 non-null   int64
 19  Allergy to dairy product  1171 non-null   int64
 20  Allergy to nut            1171 non-null   int64
 21  Allergy to bee venom      1171 non-null   int64
 22  Medications               1171 non-null   object
 23  Procedures                1165 non-null   object
dtypes: float64(6), int64(15), object(3)
memory usage: 268.7+ KB

In [186]:
final_df["Procedures"].fillna(0,inplace=True)

In [187]:
row=-1
for x in final_df["Medications"]:
    row += 1
    if(x==0):
        final_df.at[row,'Medications']=[0]

row=-1
for x in final_df["Procedures"]:
    row += 1
    if(x==0):
        final_df.at[row,'Procedures']=[0]

In [188]:
final_df

,Id,Dead,Age,MARITAL,RACE,ETHNICITY,GENDER,Latex allergy,Shellfish allergy,Allergy to mould,Dander (animal) allergy,Allergy to grass pollen,Allergy to tree pollen,Allergy to soya,Allergy to fish,House dust mite allergy,Allergy to eggs,Allergy to wheat,Allergy to peanuts,Allergy to dairy product,Allergy to nut,Allergy to bee venom,Medications,Procedures
0,1d604da9-9a81-4ba9-80c2-de3375d59b40,0.0,32.0,2.0,1.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,[562251],[430193006]
1,034e9e3b-2def-4559-bb2a-7850888ae060,0.0,37.0,2.0,1.0,1.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,[313782],[430193006]
2,10339b10-3cd1-4ac3-ac13-ec26728cb592,0.0,29.0,2.0,1.0,1.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,"[849574, 313782]","[288086009, 430193006, 269911007]"
3,8d4c4326-e9de-4f45-9a4c-f8c36bff89ae,0.0,43.0,2.0,1.0,1.0,1.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,"[389221, 978950, 748856, 1534809, 1000126]","[65200003, 76601001, 169553002, 430193006, 301..."
4,f5dcd418-09fe-4a2f-baa0-3da800bd8c3a,0.0,25.0,0.0,1.0,1.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,[313782],"[117015009, 430193006, 269911007]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1166,023a7d29-32b3-4db5-89c8-b88bd7582ec0,0.0,99.0,2.0,3.0,0.0,1.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,"[855332, 197604, 314231, 313782, 897718]","[180325003, 430193006]"
1167,1fc8dafd-90e5-44d6-9179-81156c0ea083,0.0,44.0,1.0,1.0,1.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,[834102],[430193006]
1168,6d048a56-edb8-4f29-891d-7a84d75a8e78,1.0,91.0,1.0,1.0,1.0,1.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,"[313185, 895994, 313782, 2123111]","[430193006, 35025007, 71651007, 90226004, 2699..."
1169,fca3178e-fb68-41c3-8598-702d3ca68b96,1.0,75.0,2.0,1.0,1.0,1.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,"[313988, 866414, 313782, 243670, 1719286, 2001...","[433112001, 433236007, 312681000, 73761001, 39..."
1170,fc817953-cc8b-45db-9c85-7c0ced8fa90d,0.0,107.0,2.0,1.0,1.0,1.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,[0],[430193006]

In [189]:
import csv
reader = csv.reader(open(r'C:\Users\pskir\Downloads\6180e4c10462e_Case_Files\gapdays.csv', 'r'))
d = {}
for row in reader:
   k, v = row
   d[k] = v

In [190]:
final_df["Days"] = [0]*1171

<ipython-input-190-8663b92359a8>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df["Days"] = [0]*1171

In [191]:
row = -1
for x in final_df["Days"]:
    row+=1
    if final_df.loc[row,"Id"] in d.keys():
        final_df.loc[row,"Days"] = d[final_df.loc[row,"Id"]]

D:\Anaconda\lib\site-packages\pandas\core\indexing.py:1765: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)

In [192]:
from statistics import mean

In [193]:
row=-1
for x in final_df["Medications"]:
    row += 1
    final_df.at[row,'Medications']=mean(x)
row=-1
for x in final_df["Procedures"]:
    row += 1
    final_df.at[row,'Procedures']=mean(x)

In [194]:
final_df["Medications"]=(final_df["Medications"]-final_df["Medications"].mean())/final_df["Medications"].std()
final_df["Procedures"]=(final_df["Procedures"]-final_df["Procedures"].mean())/final_df["Procedures"].std()

<ipython-input-194-3da428fdd190>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df["Medications"]=(final_df["Medications"]-final_df["Medications"].mean())/final_df["Medications"].std()
<ipython-input-194-3da428fdd190>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df["Procedures"]=(final_df["Procedures"]-final_df["Procedures"].mean())/final_df["Procedures"].std()

In [195]:
row = -1
for x in final_df["Days"]:
    row+=1
    final_df.at[row,'Days']=int(round(float(x)))

In [196]:
convert_dict = {'Medications': float,
                'Procedures': float,
                'Days': int
               }
  
final_df = final_df.astype(convert_dict)

In [197]:
final_df

,Id,Dead,Age,MARITAL,RACE,ETHNICITY,GENDER,Latex allergy,Shellfish allergy,Allergy to mould,Dander (animal) allergy,Allergy to grass pollen,Allergy to tree pollen,Allergy to soya,Allergy to fish,House dust mite allergy,Allergy to eggs,Allergy to wheat,Allergy to peanuts,Allergy to dairy product,Allergy to nut,Allergy to bee venom,Medications,Procedures,Days
0,1d604da9-9a81-4ba9-80c2-de3375d59b40,0.0,32.0,2.0,1.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-0.284477,-0.080258,2177
1,034e9e3b-2def-4559-bb2a-7850888ae060,0.0,37.0,2.0,1.0,1.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-1.151734,-0.080258,1266
2,10339b10-3cd1-4ac3-ac13-ec26728cb592,0.0,29.0,2.0,1.0,1.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-0.216669,-0.080259,485
3,8d4c4326-e9de-4f45-9a4c-f8c36bff89ae,0.0,43.0,2.0,1.0,1.0,1.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1.000486,-0.080260,527
4,f5dcd418-09fe-4a2f-baa0-3da800bd8c3a,0.0,25.0,0.0,1.0,1.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-1.151734,-0.080259,395
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1166,023a7d29-32b3-4db5-89c8-b88bd7582ec0,0.0,99.0,2.0,3.0,0.0,1.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-0.446842,-0.080259,319
1167,1fc8dafd-90e5-44d6-9179-81156c0ea083,0.0,44.0,1.0,1.0,1.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.664393,-0.080258,316
1168,6d048a56-edb8-4f29-891d-7a84d75a8e78,1.0,91.0,1.0,1.0,1.0,1.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.934606,-0.080260,525
1169,fca3178e-fb68-41c3-8598-702d3ca68b96,1.0,75.0,2.0,1.0,1.0,1.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.928516,-0.080259,1246
1170,fc817953-cc8b-45db-9c85-7c0ced8fa90d,0.0,107.0,2.0,1.0,1.0,1.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-2.246960,-0.080258,3366

In [198]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1171 entries, 0 to 1170
Data columns (total 25 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Id                        1171 non-null   object
 1   Dead                      1171 non-null   float64
 2   Age                       1171 non-null   float64
 3   MARITAL                   1171 non-null   float64
 4   RACE                      1171 non-null   float64
 5   ETHNICITY                 1171 non-null   float64
 6   GENDER                    1171 non-null   float64
 7   Latex allergy             1171 non-null   int64
 8   Shellfish allergy         1171 non-null   int64
 9   Allergy to mould          1171 non-null   int64
 10  Dander (animal) allergy   1171 non-null   int64
 11  Allergy to grass pollen   1171 non-null   int64
 12  Allergy to tree pollen    1171 non-null   int64
 13  Allergy to soya           1171 non-null   int64
 14  Allergy to fish           1171 non-null   int64
 15  House dust mite allergy   1171 non-null   int64
 16  Allergy to eggs           1171 non-null   int64
 17  Allergy to wheat          1171 non-null   int64
 18  Allergy to peanuts        1171 non-null   int64
 19  Allergy to dairy product  1171 non-null   int64
 20  Allergy to nut            1171 non-null   int64
 21  Allergy to bee venom      1171 non-null   int64
 22  Medications               1171 non-null   float64
 23  Procedures                1171 non-null   float64
 24  Days                      1171 non-null   int32
dtypes: float64(8), int32(1), int64(15), object(1)
memory usage: 273.3+ KB

In [199]:
from sklearn.model_selection import train_test_split

In [200]:
x_train,x_test,y_train,y_test = train_test_split(final_df.iloc[:,1:24].values , final_df.iloc[:,24].values)

In [201]:
from sklearn.tree import DecisionTreeRegressor

In [202]:
clf = DecisionTreeRegressor()
clf.fit(x_train,y_train)

DecisionTreeRegressor()

In [203]:
pred_y = clf.predict(x_test)

In [204]:
print(y_test)

[  88    0  252  357    0  418 1055  718  595 2194    0  455  139  312
  297 1767 1013  140    0  200 1951  812   82   64 1638 1974  288  453
   82  700  114  809   96   86  295   85  259   43 1208  218    0  517
 1049 3366   94 1990  307  179  225  251  496  278 2207  645 1405  973
  747  241  259  240 1714  861  506  240  529   52  314  644  754  295
 2223 1171    0  349 1182 1806  403  666 1062  464  221  608  498  613
  698  598  146 1414  318  942  228 1121 1521 1485 2156  397 4233  474
 2842 1081   12  353 1028    0  251  628 2383 2366  211  273 2568  929
 1901  633  255  492  650  467 1087 1441    0 2126  236  983  154 1288
    0  224 1098  820  719  348  601 1094  341 1649  260   57  703  338
  356  879 3205  307  180 2947  522 3653  592 1762 1671  636  544  694
  442   59  208   78 3299 1966  372  360   10  289  341  187  542  135
  938 1038  524    0  628  909  386  635    0  990  553 1494 1865 2373
  244  113   28   80  249  289  337  862  220 3269  528 2753  254  803
  427  415  141  222  769   30  306  206 1045  250  455 1081 1063 4220
  210  646  332  176  428  398 1862    0  509  285   94  436  317 2501
  387  324  125  787   86  376  329  643  154  400    0   11 1633 2201
  252  155  316  650 1363  458  230  378 2510 1644  111  177 1058  288
  259  319  475  581  668  388  477 1007 1224    4  228 1277   96 2906
  242 2081  408  168  205   46   52  876   45  429 1203  416    0    0
 1090   56  297   94 1502  477  517  174  613  375 3218  329    0]

In [205]:
print(pred_y)

[  84.   678.   144.   181.    15.   354.   128.    70.  4311.  3404.
    0.   470.   741.   557.   696.   470.   158.   179.     0.   179.
   45.  1264.   120.   645.  1326.   520.   158.   354.    44.   285.
  121.   498.   512.    79.  3451.   551.   181.   120.  1604.   228.
  382.   440.     0.  6874.   273.   520.   481.   551.   489.   242.
  815.   939.  1555.  1592.   675.   681.   449.    89.   140.   551.
   66.   288.   169.   190.  1688.    79.   606.  2827.   166.   585.
  195.   201.     0.   585.   227.   634.   551.    85.   634.   258.
 1552.   244.   140.   558.  1525.  1955.   219.   586.   536.   424.
    0.   608.   665.  1315.  4311.   283.   545.   270.  1759.   701.
 1688.   611.   260.     0.  1077.  1042.  2128.   552.   664.   336.
 1955.  1759.   363.   413.   283.   244.   511.  2744.   168.   829.
    0.   585.   460.  2283.   934.   697.   204.   558.  1955.   270.
  310.   267.   260.   525.  1168.   303.   157.   517.   354.   551.
  105.   260.  3787.  2344.  1688.  2140.5  179.   284.  2704.  2532.
  939.   402.  1525.   260.   478.   711.   470.   781.  1293.   272.
   69.   168.   752.   557.   205.  1300.   354.   202.   270.   697.
  949.     0.  1088.   585.   826.     0.  1046.   247.  2431.   244.
 1343.   557.  3404.   520.    57.    86.   302.   440.  1525.   270.
  127.    74.   168.  1934.  1177.   880.   181.   812.    46.   102.
 1196.    15.  2266.   470.  3049.  1788.    50.   274.   490.  3451.
  376.   646.  1688.   144.   585.     0.   281.   249.  1274.   645.
  354.   470.   608.   225.     0.  1279.   464.  3404.   200.    82.
  922.  1437.   148.  1582.   165.   144.  3926.  1535.   280.   219.
 1437.   205.   427.  1021.   135.   602.   360.  1185.   199.   181.
  479.    44.   219.  1688.   100.   360.   204.  1274.  1185.  2704.
  579.   373.   361.   376.    89.    45.   440.  2859.   812.   174.
 1363.   103.    60.   563.  2642.   551.  4323.   165.     0.     0.
  304.   162.   448.   280.   260.   360.  1196.  3616.     0.   790.
 1955.   252.   283. ]

In [206]:
#Average Error form correct value
s = 0
for i in range(len(y_test)):
    s += pred_y[i]-y_test[i]
print(s/293)

42.284982935153586